<a href="https://colab.research.google.com/github/Leon-web-net/Machine_Learning/blob/Intro%2Fbasics/Intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.1+cu118


In [2]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim
scalar.item()

7

In [4]:
# Vector
vector = torch.tensor([7,4])
vector
for i in vector:
  print(i.item())

vector.ndim

7
4


1

In [5]:
vector.shape

torch.Size([2])

In [6]:
# MATRIX
matrix = torch.tensor([[7,6],[5,5]])
matrix.ndim

2

In [7]:
matrix.shape

torch.Size([2, 2])

In [8]:
tensor = torch.tensor([[[2,2,3],[3,3,3],[3,4,4]]])
tensor[0][1]

tensor([3, 3, 3])

#Random Tensors#
Why random tensors?

Important for neural networks as they learn starting with tensors full of random numbers and adjust those to better represent the data.

`random numbers -> look at data -> update random numbers -> look at data -> update random numbers`


In [9]:
# create a random tensor of shape (3,4)
random_tensor = torch.rand(3,4,5)
random_tensor

tensor([[[0.6034, 0.8227, 0.6741, 0.3788, 0.2657],
         [0.5927, 0.9073, 0.6421, 0.2358, 0.1078],
         [0.1361, 0.9295, 0.6755, 0.4137, 0.7102],
         [0.8763, 0.9177, 0.2611, 0.7130, 0.1813]],

        [[0.4988, 0.8326, 0.9947, 0.0488, 0.2604],
         [0.1637, 0.9728, 0.8255, 0.8461, 0.7764],
         [0.2515, 0.6308, 0.8328, 0.9414, 0.5448],
         [0.3938, 0.0020, 0.2091, 0.2992, 0.9760]],

        [[0.9060, 0.4328, 0.1431, 0.6447, 0.8622],
         [0.9566, 0.0825, 0.8704, 0.8039, 0.8270],
         [0.6358, 0.7485, 0.0646, 0.8193, 0.5849],
         [0.4283, 0.6474, 0.0805, 0.1185, 0.6545]]])

Create random tensor with similar shape to Image tensor.

height width colour channel (R, G, B)

In [10]:
random_img_tensor = torch.rand(size=(3,224,224))
random_img_tensor.shape, random_img_tensor.ndim

(torch.Size([3, 224, 224]), 3)

# Zeros and Ones

In [11]:
# create a tensor of all zeros (for creating a mask)
zeros = torch.zeros(size=(3,4))
zeros[0][0]=1
zeros[1][1]=1
tensorA = torch.rand(size=(3,1))
tensorA, zeros

(tensor([[0.6449],
         [0.0411],
         [0.2727]]),
 tensor([[1., 0., 0., 0.],
         [0., 1., 0., 0.],
         [0., 0., 0., 0.]]))

In [12]:
tensorA*zeros

tensor([[0.6449, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0411, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000]])

In [13]:
zeros.dtype # default float32

torch.float32

#Creating Range of Tensors

In [14]:
# torch.arange()
one_step_ten=torch.arange(start=0,end=10,step=2)
one_step_ten

tensor([0, 2, 4, 6, 8])

In [15]:
# creating tensors like
zero_like = torch.zeros_like(input=one_step_ten)
zero_like

tensor([0, 0, 0, 0, 0])

#Tensor Datatypes

**3 Big Errors**


1.   Tensor not right datatype
2.   Tensor not right shape
1.   Tensor not on the right device



In [16]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0,6,9],
                               dtype=None,
                               device="cuda", # what device: cpu, gpu, tpu, etc
                               requires_grad=False)
float_16_tensor = torch.tensor([3.0,6,9], dtype=torch.float16, device="cuda")
float_32_tensor

tensor([3., 6., 9.], device='cuda:0')

In [17]:
float_32_tensor.dtype

torch.float32

In [18]:
float_32_tensor*float_16_tensor

tensor([ 9., 36., 81.], device='cuda:0')

#Getting information from tensor


1.   Datatype: tensor.dtype
2.   Tensor shape: tensor.shape

1.   Tensor device: tensor.device







In [19]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.4569, 0.2960, 0.8551, 0.4670],
        [0.9783, 0.1497, 0.1093, 0.2197],
        [0.9535, 0.6904, 0.3260, 0.3562]])

In [20]:
print(some_tensor.dtype, some_tensor.shape,some_tensor.device,)

torch.float32 torch.Size([3, 4]) cpu


# Tensor Operations



*   Addition
*   Subtraction
*   Multiplication
*   Division
*   Matrix multiplication



In [21]:
# Create tensor
tensor = torch.tensor([1,2,3])
# Add
tensor + 10

tensor([11, 12, 13])

In [22]:
# Sub
tensor - 10

tensor([-9, -8, -7])

In [23]:
# Multiply
tensor*10

tensor([10, 20, 30])

In [24]:
# Divide
tensor/10

tensor([0.1000, 0.2000, 0.3000])

In [25]:
# Matrix multipliaction (dot product)
tensor * tensor

tensor([1, 4, 9])

In [26]:
torch.matmul(tensor, tensor)

tensor(14)

In [27]:
%%time
value = 0
for i in range(len(tensor)):
  value+= tensor[i] *tensor[i]

print(value)

tensor(14)
CPU times: user 545 µs, sys: 0 ns, total: 545 µs
Wall time: 553 µs


In [28]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 70 µs, sys: 0 ns, total: 70 µs
Wall time: 74.6 µs


tensor(14)

In [29]:
tensor @ tensor

tensor(14)

# Matrix Multiplication

One of the most common errors in deep learning: shape errors.

Two rule in matrix multiplication:


1.   The **Inner Dimensions** must match:
      * `(3,2) @ (3,2)` won't work
      * `(2,3) @ (3,2)` will work
      * `(3,2) @ (2,3)` will work


2.   The resulting matrix has result of the **outer dimensions**
   * ` (2,3) @ (3,2)` -> `(2,2)`
   * `(2,100) @ (100,3)` -> `(2,3)`



In [30]:
torch.matmul(torch.rand(2,100), torch.rand(100,3))

tensor([[27.7071, 29.5239, 26.2748],
        [25.4458, 26.8344, 25.2525]])

In [31]:
Tensor_A = torch.rand(2,3)
Tensor_B = torch.rand(2,3)

# torch.matmul(Tensor_A, Tensor_B)  does not work

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a transpose

A **transpose** switches dimensions of given tensor

In [32]:
Tensor_A, Tensor_A.T

(tensor([[0.7026, 0.3018, 0.6235],
         [0.0141, 0.0630, 0.0537]]),
 tensor([[0.7026, 0.0141],
         [0.3018, 0.0630],
         [0.6235, 0.0537]]))

# Finding Min Max Mean Sum
(Tensor Aggregation)

In [33]:
# create tensor
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [34]:
# Find min, max
torch.min(x),torch.max(x)

(tensor(0), tensor(90))

In [35]:
# Find mean
# Common Error - Input dtype must be either a floating point or complex dtype. Got: Long
torch.mean(x.type(torch.float32))

tensor(45.)

In [36]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [37]:
# Finding positional min and max (The index)
x.argmin(), x.argmax()

(tensor(0), tensor(9))

# Reshaping Stacking Squeezing and Unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - Return aview of the input with the dimensions permuted (swapped0)in a certain way

In [38]:
# Create a tensor
import torch
x = torch.arange(1.,10.)
my_tensor = torch.rand(3,5,2)
x,x.shape , my_tensor

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 torch.Size([9]),
 tensor([[[0.6968, 0.6538],
          [0.4161, 0.7335],
          [0.8170, 0.3034],
          [0.7524, 0.5976],
          [0.8976, 0.4672]],
 
         [[0.7053, 0.6657],
          [0.0408, 0.0041],
          [0.3088, 0.1538],
          [0.3274, 0.4256],
          [0.0035, 0.9431]],
 
         [[0.8413, 0.6598],
          [0.2390, 0.2661],
          [0.6095, 0.4743],
          [0.2798, 0.5043],
          [0.5989, 0.3813]]]))

In [39]:
# Add an extra dimension
x_reshaped = x.reshape(-1,1)
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [40]:
# Change the view
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [41]:
# Changing z changes x (because a view of a tensor shares the same memory as the original)
z [:,0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [42]:
# Stack tensors
x_stacked = torch.stack([x,x,x,x], dim=1)
my_stacked = torch.stack([my_tensor,my_tensor], dim=3)
x_stacked, my_stacked

(tensor([[5., 5., 5., 5.],
         [2., 2., 2., 2.],
         [3., 3., 3., 3.],
         [4., 4., 4., 4.],
         [5., 5., 5., 5.],
         [6., 6., 6., 6.],
         [7., 7., 7., 7.],
         [8., 8., 8., 8.],
         [9., 9., 9., 9.]]),
 tensor([[[[0.6968, 0.6968],
           [0.6538, 0.6538]],
 
          [[0.4161, 0.4161],
           [0.7335, 0.7335]],
 
          [[0.8170, 0.8170],
           [0.3034, 0.3034]],
 
          [[0.7524, 0.7524],
           [0.5976, 0.5976]],
 
          [[0.8976, 0.8976],
           [0.4672, 0.4672]]],
 
 
         [[[0.7053, 0.7053],
           [0.6657, 0.6657]],
 
          [[0.0408, 0.0408],
           [0.0041, 0.0041]],
 
          [[0.3088, 0.3088],
           [0.1538, 0.1538]],
 
          [[0.3274, 0.3274],
           [0.4256, 0.4256]],
 
          [[0.0035, 0.0035],
           [0.9431, 0.9431]]],
 
 
         [[[0.8413, 0.8413],
           [0.6598, 0.6598]],
 
          [[0.2390, 0.2390],
           [0.2661, 0.2661]],
 
          [[0.609

In [43]:
# Squeeze and Unsqueeze
x_reshaped, x_reshaped.shape

(tensor([[5.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [44]:
# Squeeze -  removes extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
x_squeezed, x_squeezed.shape

(tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [45]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim
x_unsqueezed = x_squeezed.unsqueeze(dim=1)
x_unsqueezed, x_unsqueezed.shape

(tensor([[5.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [46]:
# torch.permute - rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224,224,3)) # [height, width, colour_channels]

x_permuted = x_original.permute(2,0,1)

x_original.shape, x_permuted.shape

(torch.Size([224, 224, 3]), torch.Size([3, 224, 224]))

# Indexing (selecting data from Tensors)



In [47]:
# Create tensor
import torch
x = torch.arange(1,10).reshape(1,3,3)
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [48]:
# Index on new tensor
x[0,:-1,:-1]

tensor([[1, 2],
        [4, 5]])

In [49]:
# Get all values of 0th and 1st dim but only 1 index of 2nd dim
x[:,:,1]

tensor([[2, 5, 8]])

In [50]:
# Get all values of the 0 dim but only the 1 index value of 1st and 2nd dimension
x[:,1,1]

tensor([5])

In [51]:
# Get index 0 of 0th and 1st dim and all values of 2nd dim
x[0,0,:]

tensor([1, 2, 3])

In [52]:
x[0,-1,-1], x[0,:,-1]

(tensor(9), tensor([3, 6, 9]))

# Pytorch tensors and NumPy

* Data in Numpy, want in Pytorch tensor -> `torch.from_numpy(ndarray)`
* Pytorch tensor -> Numpy -> `torch.Tensor.numpy()`

Be Careful:
 * PyTorch default dtype = `float32`
 * Numpy default dtype = `float64`

In [1]:
import torch
import numpy as np

array = np.arange(1.0,8)
tensor = torch.from_numpy(array).type(torch.float32) # numpy to torch will be float 64 unless specified

array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [2]:
# Change the value of array, what will this do to `tensor`?
array +=1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [3]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()  # torch to numpy will be float32 unless specified
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [4]:
# Change tensor, what happens to `numpy_tensor` ?
tensor = tensor +1
numpy_tensor, tensor

(array([1., 1., 1., 1., 1., 1., 1.], dtype=float32),
 tensor([2., 2., 2., 2., 2., 2., 2.]))

In [5]:
# In place operations will affect both numpy and tensor
# This will not apply if you use tensor = tensor + 1 as you create a new tensor by doing this
# which also changes memory address so in place affects the new tensor
tensor+=1
numpy_tensor, tensor

(array([1., 1., 1., 1., 1., 1., 1.], dtype=float32),
 tensor([3., 3., 3., 3., 3., 3., 3.]))

# Reproducibility
( try to take out random out of random)

To reduce randomness in NN and pytorh we use **random seed**.


In [6]:
torch.rand(3,3)

tensor([[0.8672, 0.6896, 0.0667],
        [0.5976, 0.7071, 0.0837],
        [0.6761, 0.0709, 0.0954]])

In [7]:
import torch

# create 2 rand tensors
rand_tensor_A = torch.rand(3,4)
rand_tensor_B = torch.rand(3,4)

print(rand_tensor_A, rand_tensor_B)
print(rand_tensor_A == rand_tensor_B)

tensor([[0.5998, 0.5033, 0.7981, 0.0966],
        [0.3397, 0.0323, 0.8376, 0.1183],
        [0.2592, 0.1124, 0.4829, 0.9019]]) tensor([[0.0683, 0.2745, 0.1746, 0.9849],
        [0.5460, 0.6577, 0.0666, 0.6965],
        [0.9283, 0.7475, 0.3182, 0.1150]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [8]:
# Make random but reproducibile tensors
import torch

# Set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)

random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C, random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]]) tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


# Accessing GPU

GPU -> faster computation on numbers

Getting a GPU

1. Google Colab for free GPU
2. Use own GPU
3. Cloud computing - GCP, AWS, Azure rent computers on cloud

In [9]:
!nvidia-smi

Thu Oct 19 00:44:03 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   48C    P8    10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

Check GPU access

In [12]:
# Check for GPU access with Pytorch
import torch
torch.cuda.is_available(), torch.cuda.device_count()

(True, 1)

In [11]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'