<a href="https://colab.research.google.com/github/Leon-web-net/Machine_Learning/blob/Intro%2Fbasics/Intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.1+cu118


In [2]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim
scalar.item()

7

In [4]:
# Vector
vector = torch.tensor([7,4])
vector
for i in vector:
  print(i.item())

vector.ndim

7
4


1

In [5]:
vector.shape

torch.Size([2])

In [6]:
# MATRIX
matrix = torch.tensor([[7,6],[5,5]])
matrix.ndim

2

In [7]:
matrix.shape

torch.Size([2, 2])

In [8]:
tensor = torch.tensor([[[2,2,3],[3,3,3],[3,4,4]]])
tensor[0][1]

tensor([3, 3, 3])

#Random Tensors#
Why random tensors?

Important for neural networks as they learn starting with tensors full of random numbers and adjust those to better represent the data.

`random numbers -> look at data -> update random numbers -> look at data -> update random numbers`


In [9]:
# create a random tensor of shape (3,4)
random_tensor = torch.rand(3,4,5)
random_tensor

tensor([[[0.8458, 0.7010, 0.6399, 0.5297, 0.7461],
         [0.9747, 0.4462, 0.6449, 0.7338, 0.6773],
         [0.9276, 0.9688, 0.1040, 0.4597, 0.3061],
         [0.2036, 0.1149, 0.8970, 0.1870, 0.5470]],

        [[0.7047, 0.6799, 0.6029, 0.9200, 0.4302],
         [0.6008, 0.3640, 0.7177, 0.2870, 0.2759],
         [0.2225, 0.2305, 0.5579, 0.7096, 0.2334],
         [0.3939, 0.8852, 0.3361, 0.6965, 0.7806]],

        [[0.7251, 0.5556, 0.5432, 0.2851, 0.6216],
         [0.6535, 0.4563, 0.0846, 0.8550, 0.9584],
         [0.3325, 0.2588, 0.8462, 0.9571, 0.3156],
         [0.2946, 0.1064, 0.8958, 0.9392, 0.5530]]])

Create random tensor with similar shape to Image tensor.

height width colour channel (R, G, B)

In [10]:
random_img_tensor = torch.rand(size=(3,224,224))
random_img_tensor.shape, random_img_tensor.ndim

(torch.Size([3, 224, 224]), 3)

# Zeros and Ones

In [11]:
# create a tensor of all zeros (for creating a mask)
zeros = torch.zeros(size=(3,4))
zeros[0][0]=1
zeros[1][1]=1
tensorA = torch.rand(size=(3,1))
tensorA, zeros

(tensor([[0.9758],
         [0.6190],
         [0.6545]]),
 tensor([[1., 0., 0., 0.],
         [0., 1., 0., 0.],
         [0., 0., 0., 0.]]))

In [12]:
tensorA*zeros

tensor([[0.9758, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.6190, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000]])

In [13]:
zeros.dtype # default float32

torch.float32

#Creating Range of Tensors

In [14]:
# torch.arange()
one_step_ten=torch.arange(start=0,end=10,step=2)
one_step_ten

tensor([0, 2, 4, 6, 8])

In [15]:
# creating tensors like
zero_like = torch.zeros_like(input=one_step_ten)
zero_like

tensor([0, 0, 0, 0, 0])

#Tensor Datatypes

**3 Big Errors**


1.   Tensor not right datatype
2.   Tensor not right shape
1.   Tensor not on the right device



In [16]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0,6,9],
                               dtype=None,
                               device="cuda", # what device: cpu, gpu, tpu, etc
                               requires_grad=False)
float_16_tensor = torch.tensor([3.0,6,9], dtype=torch.float16, device="cuda")
float_32_tensor

tensor([3., 6., 9.], device='cuda:0')

In [17]:
float_32_tensor.dtype

torch.float32

In [18]:
float_32_tensor*float_16_tensor

tensor([ 9., 36., 81.], device='cuda:0')

#Getting information from tensor


1.   Datatype: tensor.dtype
2.   Tensor shape: tensor.shape

1.   Tensor device: tensor.device







In [19]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.1806, 0.2982, 0.5328, 0.3880],
        [0.9181, 0.8034, 0.6194, 0.8589],
        [0.9001, 0.0057, 0.7831, 0.1400]])

In [20]:
print(some_tensor.dtype, some_tensor.shape,some_tensor.device,)

torch.float32 torch.Size([3, 4]) cpu


# Tensor Operations



*   Addition
*   Subtraction
*   Multiplication
*   Division
*   Matrix multiplication



In [21]:
# Create tensor
tensor = torch.tensor([1,2,3])
# Add
tensor + 10

tensor([11, 12, 13])

In [22]:
# Sub
tensor - 10

tensor([-9, -8, -7])

In [23]:
# Multiply
tensor*10

tensor([10, 20, 30])

In [24]:
# Divide
tensor/10

tensor([0.1000, 0.2000, 0.3000])

In [25]:
# Matrix multipliaction (dot product)
tensor * tensor

tensor([1, 4, 9])

In [26]:
torch.matmul(tensor, tensor)

tensor(14)

In [27]:
%%time
value = 0
for i in range(len(tensor)):
  value+= tensor[i] *tensor[i]

print(value)

tensor(14)
CPU times: user 1.04 ms, sys: 7 µs, total: 1.04 ms
Wall time: 1.07 ms


In [28]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 26 µs, sys: 7 µs, total: 33 µs
Wall time: 35.3 µs


tensor(14)

In [29]:
tensor @ tensor

tensor(14)

# Matrix Multiplication

One of the most common errors in deep learning: shape errors.

Two rule in matrix multiplication:


1.   The **Inner Dimensions** must match:
      * `(3,2) @ (3,2)` won't work
      * `(2,3) @ (3,2)` will work
      * `(3,2) @ (2,3)` will work


2.   The resulting matrix has result of the **outer dimensions**
   * ` (2,3) @ (3,2)` -> `(2,2)`
   * `(2,100) @ (100,3)` -> `(2,3)`



In [30]:
torch.matmul(torch.rand(2,100), torch.rand(100,3))

tensor([[26.7740, 23.1778, 24.4927],
        [27.7882, 24.4227, 26.3891]])

In [31]:
Tensor_A = torch.rand(2,3)
Tensor_B = torch.rand(2,3)

# torch.matmul(Tensor_A, Tensor_B)  does not work

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a transpose

A **transpose** switches dimensions of given tensor

In [32]:
Tensor_A, Tensor_A.T

(tensor([[0.9409, 0.6852, 0.4049],
         [0.6063, 0.2018, 0.1903]]),
 tensor([[0.9409, 0.6063],
         [0.6852, 0.2018],
         [0.4049, 0.1903]]))

# Finding Min Max Mean Sum
(Tensor Aggregation)

In [34]:
# create tensor
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [36]:
# Find min, max
torch.min(x),torch.max(x)

(tensor(0), tensor(90))

In [39]:
# Find mean
# Common Error - Input dtype must be either a floating point or complex dtype. Got: Long
torch.mean(x.type(torch.float32))

tensor(45.)

In [41]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))