<a href="https://colab.research.google.com/github/Leon-web-net/Machine_Learning/blob/Intro%2Fbasics/Intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.1+cu118


In [2]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim
scalar.item()

7

In [4]:
# Vector
vector = torch.tensor([7,4])
vector
for i in vector:
  print(i.item())

vector.ndim

7
4


1

In [5]:
vector.shape

torch.Size([2])

In [6]:
# MATRIX
matrix = torch.tensor([[7,6],[5,5]])
matrix.ndim

2

In [7]:
matrix.shape

torch.Size([2, 2])

In [8]:
tensor = torch.tensor([[[2,2,3],[3,3,3],[3,4,4]]])
tensor[0][1]

tensor([3, 3, 3])

#Random Tensors#
Why random tensors?

Important for neural networks as they learn starting with tensors full of random numbers and adjust those to better represent the data.

`random numbers -> look at data -> update random numbers -> look at data -> update random numbers`


In [9]:
# create a random tensor of shape (3,4)
random_tensor = torch.rand(3,4,5)
random_tensor

tensor([[[0.4203, 0.0921, 0.4392, 0.9858, 0.4640],
         [0.4064, 0.8028, 0.5873, 0.9868, 0.8370],
         [0.5205, 0.6624, 0.5742, 0.9543, 0.1590],
         [0.4088, 0.9998, 0.0064, 0.9690, 0.6471]],

        [[0.0866, 0.1727, 0.1340, 0.6709, 0.1161],
         [0.2809, 0.8061, 0.7723, 0.9705, 0.3841],
         [0.0425, 0.8160, 0.3688, 0.4006, 0.5095],
         [0.2641, 0.2829, 0.1458, 0.3890, 0.2013]],

        [[0.3871, 0.5821, 0.6457, 0.6762, 0.9858],
         [0.1782, 0.1475, 0.1624, 0.4234, 0.9558],
         [0.4508, 0.1019, 0.2889, 0.1041, 0.4975],
         [0.1603, 0.1173, 0.4162, 0.5644, 0.5025]]])

Create random tensor with similar shape to Image tensor.

height width colour channel (R, G, B)

In [10]:
random_img_tensor = torch.rand(size=(3,224,224))
random_img_tensor.shape, random_img_tensor.ndim

(torch.Size([3, 224, 224]), 3)

# Zeros and Ones

In [11]:
# create a tensor of all zeros (for creating a mask)
zeros = torch.zeros(size=(3,4))
zeros[0][0]=1
zeros[1][1]=1
tensorA = torch.rand(size=(3,1))
tensorA, zeros

(tensor([[0.7715],
         [0.3516],
         [0.0409]]),
 tensor([[1., 0., 0., 0.],
         [0., 1., 0., 0.],
         [0., 0., 0., 0.]]))

In [12]:
tensorA*zeros

tensor([[0.7715, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.3516, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000]])

In [13]:
zeros.dtype # default float32

torch.float32

#Creating Range of Tensors

In [14]:
# torch.arange()
one_step_ten=torch.arange(start=0,end=10,step=2)
one_step_ten

tensor([0, 2, 4, 6, 8])

In [15]:
# creating tensors like
zero_like = torch.zeros_like(input=one_step_ten)
zero_like

tensor([0, 0, 0, 0, 0])

#Tensor Datatypes

**3 Big Errors**


1.   Tensor not right datatype
2.   Tensor not right shape
1.   Tensor not on the right device



In [19]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0,6,9],
                               dtype=None,
                               device="cuda", # what device: cpu, gpu, tpu, etc
                               requires_grad=False)
float_16_tensor = torch.tensor([3.0,6,9], dtype=torch.float16, device="cuda")
float_32_tensor

tensor([3., 6., 9.], device='cuda:0')

In [17]:
float_32_tensor.dtype

torch.float32

In [20]:
float_32_tensor*float_16_tensor

tensor([ 9., 36., 81.], device='cuda:0')